language: objective-c
osx_image: xcode11
xcode_project: RESTAPI.xcodeproj
xcode_scheme: RESTAPI
xcode_sdk: iphonesimulator12.2
env:
  global:
  - FRAMEWORK_NAME=RESTAPI
  - IMAGE_FRAMEWORK_NAME=RESTAPIImage
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
before_script:
- carthage update
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
- carthage archive $IMAGE_FRAMEWORK_NAME
script:
- set -o pipefail
- travis_retry xcodebuild -scheme 'RESTAPI iOS' -destination 'platform=iOS Simulator,name=iPhone 8' build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
- travis_retry xcodebuild -scheme 'RESTAPI tvOS' -destination 'platform=tvOS Simulator,name=Apple TV' build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_RELEASE_KEY
  file:
    - "$FRAMEWORK_NAME.framework.zip"
    - "$IMAGE_FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: Gujci/RESTAPI
    tags: true
notifications:
  slack:
    rooms:
      - gujci: ${SLACK_WORKSPACE}#restapi
  email: false
