name: ios-spm

on: [push]

jobs:
  test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: SPM test
      run: swift test
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.app/Contents/Developer
